behaviors:
  IrBateria:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.98
        strength: 1.0
        learning_rate: 1e-4
    keep_checkpoints: 5
    max_steps: 150000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
environment_parameters:
  chargerDistance:
    curriculum:
      - name: lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: IrBateria
          signal_smoothing: true
          min_lesson_length: 100
          threshold: -2
        value: 10
      - name: lesson2 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: IrBateria
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 7.0
            max_value: 9.0
      - name: lesson3 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: IrBateria
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 5
          require_reset: true
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 4.0
            max_value: 7.0
      - name: lesson3
        value: 2.0
